name: Migrate to prod (sql)

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }} # Production or primary database
  PG_VERSION: '16'

jobs:
  pr-merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Ensure the PR was merged

    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          git diff --name-only -r HEAD^1 HEAD > migration_files.txt
          echo "Changed files:"
          cat migration_files.txt

      - name: Apply migrations
        run: |
          while IFS= read -r file; do
            if [ ! -f "$file" ]; then
              echo "$file does not exist"
              continue
            fi

            if [[ "$file" != *.sql ]]; then
              echo "$file is not a SQL file"
              continue
            fi

            echo "Processing $file"
            if ! /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/psql "${{ env.PROD_DATABASE_URL }}" < "$file"; then
              echo "Error applying $file"
              exit 1
            fi
          done < migration_files.txt
